language: php
sudo: required

# PHP Support see: http://php.net/supported-versions.php
# HHVM Support see: https://docs.hhvm.com/hhvm/installation/introduction#lts-releases
matrix:
  include:
    # Drop PHP 5.6 on 31 Dec 2018
    - php: '5.6'
    # Drop PHP 7.0 on 3 Dec 2018
    - php: '7.0'
    - php: '7.1'
    # Drop HHVM 3.12 on 29 Dec 2016
    - php: hhvm-3.12
      dist: trusty
      group: edge
    # Drop HHVM 3.15 on 15 Jun 2017
    - php: hhvm-3.15
      dist: trusty
      group: edge
    # Add HHVM 3.18 on 13 Feb 2017
    # - hhvm-3.18


install:
  - composer install

after_success:
  # Send code coverage to codecov.io for further investigations.
  - bash <(curl -s https://codecov.io/bash)

script:
  # Assert composer.json is clean
  - composer validate --strict
  # Run unit tests
  - opt/bin/phpunit -c etc/phpunit.xml --coverage-clover=var/phpunit/coverage.xml --coverage-text
  # CodeSniffer
  - opt/bin/phpcs --config-set installed_paths opt/escapestudios/symfony2-coding-standard
  - opt/bin/phpcs --standard=etc/phpcs.xml lib
